apiVersion: v1
data:
  minkms: |
    image: "quay.io/minio/aistor/minkms:RELEASE.2025-11-12T19-14-51Z"
  minkms-sidecar: |
    image: "quay.io/minio/aistor/minkms-sidecar:RELEASE.2026-02-08T21-05-50Z"
kind: ConfigMap
metadata:
  name: minkms-operator-default
