---
catalog_templates:
  - template_name: v4.19.yaml
    channels: [stable]
    replaces: intel-device-plugins-operator.v0.34.1
  - template_name: v4.20.yaml
    channels: [stable]
    replaces: intel-device-plugins-operator.v0.34.1
  - template_name: v4.21.yaml
    channels: [stable]
    replaces: intel-device-plugins-operator.v0.34.1
  - template_name: v4.22.yaml
    channels: [stable]
    replaces: intel-device-plugins-operator.v0.34.1
